version: '3.4'

services:
  restapidocker:
    image: mcherkaoui/nlayersapp-demos:dev
    network_mode: host 
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_PW
    env_file: .env
    depends_on:
      - db
    ports:
      - 80:80
      - 443:443
      
  db:
    image: mcr.microsoft.com/mssql/server
    volumes:
      - mssql-server-data:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "${DB_PW}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

volumes:
  mssql-server-data: {}
